name: calendar_picker_ghe
description: A lightweight Gregorian, Hijri, and Ethiopian Calendar date picker which is simple to use with a unified system.
version: 2.0.0
homepage: https://github.com/HalidAwell/calendar_picker_ghe
repository: https://github.com/HalidAwell/calendar_picker_ghe
issue_tracker: https://github.com/HalidAwell/calendar_picker_ghe/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ethiopian_datetime: ^1.0.3 # For Ethiopian calendar conversion
  hijri: ^3.0.0  # For Hijri calendar conversion

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/screenshots/

topics:
  - calendar-converter
  - gregorian-date-picker
  - hijri-date-picker
  - ethiopian-date-picker
  - localization

license: Apache-2.0
exclude:
  - lib/main.dart

