class LocalizedStrings {
  static const _localizedValues = {
    'en': {
      "january": "January",
      "february": "February",
      "march": "March",
      "april": "April",
      "may": "May",
      "june": "June",
      "july": "July",
      "august": "August",
      "september": "September",
      "october": "October",
      "november": "November",
      "december": "December",
      "meskerem": "Meskerem",
      "tikimt": "Tikimt",
      "hidar": "Hidar",
      "tahsas": "Tahsas",
      "tir": "Tir",
      "yekatit": "Yekatit",
      "megabit": "Megabit",
      "miazia": "Miazia",
      "ginbot": "Ginbot",
      "sene": "Sene",
      "hamle": "Hamle",
      "nehasse": "Nehasse",
      "pagumen": "Pagumen",
      "muharram": "Muharram",
      "safar": "Safar",
      "rabiAlAwwal": "Rabi al-Awwal",
      "rabiAlThani": "Rabi al-Thani",
      "jumadaAlAwwal": "Jumada al-Awwal",
      "jumadaAlThaniyah": "Jumada al-Thaniyah",
      "rajab": "Rajab",
      "shaban": "Sha’ban",
      "ramadan": "Ramadan",
      "shawwal": "Shawwal",
      "dhulQadah": "Dhul-Qa’dah",
      "dhulHijjah": "Dhul-Hijjah",
      "mon": "Mo",
      "tue": "Tu",
      "wed": "We",
      "thu": "Th",
      "fri": "Fr",
      "sat": "Sa",
      "sun": "Su",
      "gregorianDatePicker": "Gregorian Date Picker",
      "ethiopianDatePicker": "Ethiopian Date Picker",
      "hijriDatePicker": "Hijri Date Picker",
      "today": "Today:",
      "ok": "Ok",
      "cancel": "Cancel",
    },
    'am': {
      "january": "ጃንዋሪ",
      "february": "ፌብሩወሪ",
      "march": "ማርች",
      "april": "ኤፕሪል",
      "may": "ሜይ",
      "june": "ጁን",
      "july": "ጁላይ",
      "august": "ኦገስት",
      "september": "ሴፕቴምበር",
      "october": "ኦክቶበር",
      "november": "ኖቬምበር",
      "december": "ዲሴምበር",
      "meskerem": "መስከረም",
      "tikimt": "ጥቅምት",
      "hidar": "ህዳር",
      "tahsas": "ታኅሣሥ",
      "tir": "ጥር",
      "yekatit": "የካቲት",
      "megabit": "መጋቢት",
      "miazia": "ሚያዝያ",
      "ginbot": "ግንቦት",
      "sene": "ሰኔ",
      "hamle": "ሐምሌ",
      "nehasse": "ነሐሴ",
      "pagumen": "ጳጉሜን",
      "muharram": "ሙሐረም",
      "safar": "ሰፈር",
      "rabiAlAwwal": "ረቢዕ አል-አወል",
      "rabiAlThani": "ረቢዕ አል-ሳኒ",
      "jumadaAlAwwal": "ጁማዳ አል-አውዋል",
      "jumadaAlThaniyah": "ጁማዳ አል-ሳኒያ",
      "rajab": "ረጀብ",
      "shaban": "ሻዕባን",
      "ramadan": "ረመዷን",
      "shawwal": "ሸዋል",
      "dhulQadah": "ዙል ቃዒዳ",
      "dhulHijjah": "ዙል ሂጃ",
      "mon": "ሰኞ",
      "tue": "ማክ",
      "wed": "ረቡ",
      "thu": "ሀሙ",
      "fri": "አር",
      "sat": "ቅዳ",
      "sun": "እሁ",
      "gregorianDatePicker": "የግሪጎሪያን ቀን መምረጫ",
      "ethiopianDatePicker": "የኢትዮጵያ ቀን መምረጫ",
      "hijriDatePicker": "የሂጅሪ ቀን መምረጫ",
      "today": "ዛሬ፦",
      "ok": "እሺ",
      "cancel": "ሰርዝ",
    },
    'ar': {
      "january": "يَنايِر",
      "february": "فَبْرايِر",
      "march": "مارِس",
      "april": "أَبْريل",
      "may": "مايو",
      "june": "يونْيو",
      "july": "يولْيو",
      "august": "أَغُسْطُس",
      "september": "سِبْتَمْبَر",
      "october": "أُكْتوبَر",
      "november": "نوفَمْبَر",
      "december": "ديسَمْبَر",
      "meskerem": "مِسْكَرَمْ",
      "tikimt": "تِكِمْتْ",
      "hidar": "هِدارْ",
      "tahsas": "تَحْساسْ",
      "tir": "طِرْ",
      "yekatit": "يَكاتِيتْ",
      "megabit": "مِغابِيتْ",
      "miazia": "مِيازِيا",
      "ginbot": "جِينْبوتْ",
      "sene": "سِنِّ",
      "hamle": "هَامْلِه",
      "nehasse": "نِهَاسِّي",
      "pagumen": "بَغُومِنْ",
      "muharram": "مُحَرَّم",
      "safar": "صَفَر",
      "rabiAlAwwal": "رَبِيعُ ٱلْأَوَّل",
      "rabiAlThani": "رَبِيعُ ٱلثَّانِي",
      "jumadaAlAwwal": "جُمَادَى ٱلْأُولَى",
      "jumadaAlThaniyah": "جُمَادَى ٱلثَّانِيَة",
      "rajab": "رَجَب",
      "shaban": "شَعْبَان",
      "ramadan": "رَمَضَان",
      "shawwal": "شَوَّال",
      "dhulQadah": "ذُو ٱلْقَعْدَة",
      "dhulHijjah": "ذُو ٱلْحِجَّة",
      "mon": "الإِثْ",
      "tue": "الثُّ",
      "wed": "الأَرْ",
      "thu": "الخَ",
      "fri": "الجُ",
      "sat": "السَّ",
      "sun": "الأَ",
      "gregorianDatePicker": "مُنْتَقِي التَّارِيخِ الْمِيْلَادِيِّ",
      "ethiopianDatePicker": "مُنْتَقِي التَّارِيخِ الْإِثْيُوبِيِّ",
      "hijriDatePicker": "مُنْتَقِي التَّارِيخِ الْهِجْرِيِّ",
      "today": "الْيَوْمَ:",
      "ok": "مُوَافِق",
      "cancel": "إِلْغَاء",
    },
  };
  static String get(String langCode, String key) {
    return _localizedValues[langCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}
